### PR TITLE
Set variables dynamically 

### PR DESCRIPTION
**Pull request by barmac**
This allows to update variables dynamically via `Editor#setVariables` method.

Related to https://github.com/bpmn-io/properties-panel/issues/196

### CODE REVIEW

**Comment by barmac** [comment]
I love how easy it is to replace extensions on fly in Codemirror 6. It's well documented too: https://codemirror.net/examples/config/#top-level-reconfiguration

**Comment by nikku** [comment]
Would be great to sync this with our other editor tooling support @marstamm.

**Comment by marstamm** [comment]
Similar to: https://github.com/bpmn-io/properties-panel/issues/196#issuecomment-1321850639 :

When updating the list while a completion is active, the display flickers.  
Recording 2022-11-21 at 11 59 11 (1)

I think we should not reconfigure the whole extension but use a facet to store the configuration. This will keep the variables when a menu is already open, but use the new ones on the next character/completion.

Recording 2022-11-21 at 12 45 04

cf. example implementation in [aed6c9a](https://github.com/bpmn-io/feel-editor/pull/33/commits/aed6c9a41256c221a6568085fbefac7ba3ca5dde)

**Comment by barmac** [comment]
I need to research the facets in codemirror yet and will come back after I understand the topic. Thanks for the implementation.

**Comment by barmac** [comment]
So based on the docs (https://codemirror.net/docs/ref/#state.Facet), the autocompletion plugin will take the variables from the editor config. When editor config changes, it won't be rebuilt but rather just update its state based on new variables. I think this makes sense and will adjust the test case to that.

**Comment by barmac** [comment]
@marstamm Please check now.

**Review by marstamm — APPROVED** [review]

**Pull request merged**
