### PR TITLE
Restrict tooltip placement

### PR DESCRIPTION
**Pull request by marstamm**
Allows us to optionally add a container element where tooltips will be placed.

Recording 2022-11-18 at 16 26 25

related to https://github.com/camunda/camunda-modeler/issues/3216

Try it out on the properties-panel feature branch:
`npx @bpmn-io/sr bpmn-io/bpmn-js-properties-panel#restrict-feel-tooltip-placement`

### CODE REVIEW

**Comment by philippfromme** [comment]
I tried out the feature branch and noticed that the FEEL editor loses focus whenever I type (I disabled [Grammarly](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/810) so it's not that). Does it work for you, @marstamm?

**Comment by marstamm** [comment]
I can reproduce it. The issue was the way we create the context in the properties-panel (cf. https://github.com/bpmn-io/bpmn-js-properties-panel/pull/814/commits/b1bb19655ac4f359804a2b52ef5efcec4e234925)

**Comment by marstamm** [comment]
Should be fixed now

**Review by philippfromme — APPROVED** [review]
✅

**Pull request merged**
