### PR TITLE
feat: allow to provide functions with snippet autocompletion

### LINKED ISSUE #50: Allow to provide functions with snippet autocompletion
### Is your feature request related to a problem? Please describe.

Right now, only built-in functions are provided as snippets in the editor. Even when I pass a function signature via `name` property, it is pasted without a way to provide parameters easily. Also, the type is hardcoded as "variable":

https://github.com/bpmn-io/feel-editor/assets/28307541/34c8a554-86cd-4bf1-a819-2887f048eaaf

### Describe the solution you'd like

* [ ] I can pass a variable of type "function" and see appropriate icon.
* [ ] I can pass `params` next to the function as an array of `{ name: string, type: string }` which are used in a snippet autocompletion.

Example:

```json
{
  "name": "Compute credit score",
  "type": "function",
  "detail": "number",
  "params": [
    {
      "name": "first",
      "type": "Number"
    },
    {
      "name": "second",
      "type": "string"
    }
  ]
}
```

localhost_9876_debug html

### Describe alternatives you've considered

One could pass a function signature like it's done with the builtins, but that would be error-prone:

```json
{
  "label": "Compute credit score(first: Number, second: string)",
  "type": "function"
}
```

### Additional context

Required for https://github.com/bpmn-io/dmn-js/issues/827

### PR DESCRIPTION
**Pull request by barmac**
https://github.com/bpmn-io/feel-editor/assets/28307541/e3cbefe3-0fb7-453c-8664-0185424a475d

Closes #50

### CODE REVIEW

**Comment by barmac** [comment]
I made the unnamed parameters count from __1__ in the FEEL way, so in the capture the parameter should be called __param_4__

**Comment by barmac** [comment]
> > I made the unnamed parameters count from 1 in the FEEL way, so in the capture the parameter should be called param_4
> 
> Any specific reason for that? What does that optimize for?

I thought it looks weird to have a `param_0`, but anyway it's an edge case. I can remove it as well.

**Comment by nikku** [comment]
I now understand what you mean, I think: The name of the first unnamed parameter will be indexed in the feel way during completion. I think this makes sense. What also makes sense is to call the parameter `param4` or `param 4` as underscore is not a notion that is native to FEEL.

**Comment by barmac** [comment]
OK, let's use space then.

**Review by nikku — APPROVED** [review]
Good stuff.

**Pull request merged**
