### PR TITLE
fix: added new built-in functions

### PR DESCRIPTION
**Pull request by abdul99ahad**
### Proposed Changes
Added new functions 

- [is empty()](https://docs.camunda.io/docs/next/components/modeler/feel/builtin-functions/feel-built-in-functions-list/#is-emptylist)
- [trim()](https://docs.camunda.io/docs/next/components/modeler/feel/builtin-functions/feel-built-in-functions-string/#trimstring)
- [uuid()](https://docs.camunda.io/docs/next/components/modeler/feel/builtin-functions/feel-built-in-functions-string/#uuid)
- [to base64()](https://docs.camunda.io/docs/next/components/modeler/feel/builtin-functions/feel-built-in-functions-string/#to-base64value)

 

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] **Brief textual description** of the changes present
* [ ] **Visual demo** attached
* [ ] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

Related to: https://github.com/camunda/camunda-modeler/issues/4500

### CODE REVIEW

**Review by nikku — APPROVED** [review]
Good stuff. 

Needs release and integration. Do you take that over?

**Comment by abdul99ahad** [comment]
> Good stuff.
> 
> Needs release and integration. Do you take that over?

Yes, I would love to.

**Comment by nikku** [comment]
Taking it over now :leaves:

**Comment by nikku** [comment]
Released as https://github.com/bpmn-io/feel-editor/releases/tag/v1.9.0.

**Pull request merged**
